services:
  slivka-bio:
    image: docker.io/drsasp/slivka-bio:${SLIVKA_BIO_TAG:-latest}
    ports:
      - "4040:4040"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/slivka
    volumes:
      - media:/opt/slivka/media

  mongo:
    image: docker.io/library/mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  jupyter:
    profiles: ["jupyter"]
    image: docker.io/jupyter/base-notebook:latest
    volumes:
      - ./demo:/home/jovyan
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  media:
  mongo_data:
