version: '3.8'

services:
  slivka-bio:
    image: stuartmac/slivka-bio
    volumes:
      - media:/app/media
    ports:
      - "8080:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/slivka

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  media:
  mongo_data:
