services:
  slivka-bio:
    image: stuartmac/slivka-bio:latest
    platform: linux/amd64
    volumes:
      - media:/app/media
    ports:
      - "8080:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/slivka

  mongo:
    image: arm64v8/mongo:latest
    platform: linux/arm64/v8
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  media:
  mongo_data:
