name: slivka-bio-dev

services:
  slivka-bio:
    build:
      context: ../       # One level up
      dockerfile: slivka-bio-docker/Dockerfile
    volumes:
      - media:/opt/slivka/media
    ports:
      - "4040:4040"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/slivka

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  media:
  mongo_data:
